### ISSUE TITLE
Opening two or more instances reveals exception

### ISSUE THREAD

**Issue by VoxelDoesCode** [googlefonts/fontra-pak#54]
When you open two or more instances of Fontra Pak, you're met with an exception. The error window can be easily closed and opening files works perfectly on all Fontra Pak windows. Have not tested for editing .ufo files on multiple instances yet.

### Failed to execute script 'FontraPakMain' due to unhandled exception: 'NoneType' has no attribute 'write'
```
Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "FontraPakMain.py", line 155, in runFontraServer
  File "fontra\core\server.py", line 110, in run
    web.run_app(self.httpApp, host=host, port=httpPort)
  File "aiohttp\web.py", line 516, in run_app
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "aiohttp\web.py", line 415, in _run_app
  File "aiohttp\web_runner.py", line 121, in start
  File "asyncio\base_events.py", line 1519, in create_server
OSError: [Errno 10048] error while attempting to bind on address ('::1', 8000, 0, 0): only one usage of each socket address (protocol/network address/port) is normally permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "FontraPakMain.py", line 181, in <module>
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 52, in _freeze_support
  File "multiprocessing\spawn.py", line 116, in spawn_main
  File "multiprocessing\spawn.py", line 129, in _main
  File "multiprocessing\process.py", line 329, in _bootstrap
AttributeError: 'NoneType' object has no attribute 'write'

```

## OS Info:
**Edition:** Windows 10 Education
**Version:** 22H2
**Installed on:** 3/‎1/‎2023
**OS build:** 19045.3448
**Experience:** Windows Feature Experience Pack 1000.19044.1000.0

**Comment by VoxelDoesCode** [comment]
> why do you start two instances in the first place?

Because I forgot I already had one open. I should remember closing a Fontra browser tab and closing the Fontra Pak executable are two different things. My mistake, simply.

**Comment by justvanrossum** [comment]
To me it is interesting that that is even possible... Thanks for the report, I'll try to fix.
